PEN:- 240840116034

Practical - 1

Aim:- Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON les using Pandas.



STEP 1 : IMPORT THE PANDAS LIBRARY

In [5]:
# import pandas
import pandas as pd

STEP 2 : CREATE SAMPLE DATA

In [6]:
# create a student dataset
data = {
     "ID": [101, 102, 103, 104, 105, 106],
     "Name": ["Himay", "Janvi", "bhavya", "kavy", "dharmik", "sneh"],
     "Age": [20, 22, 24, 25, 30, 32],
     "City": ["surat","navsari","valsad","vapi","gandhinagar","Delhi"],
     "Marks": [85, 92, 78, 88, 84, 90]
       }

STEP 3: CREATE A DATAFRAME

In [51]:
# Create a DataFrame from the given data and dispaly the data
df = pd.DataFrame(data)

df

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 4 : SAVE DATA AS A CSV FILE

In [50]:
# save data in "students.csv" file
df.to_csv("students.csv", index=False)

print("csv file created successfully.")

csv file created successfully.

STEP 5 : SAVE DATA AS A EXCEL FILE

In [49]:
# save data in "students.xlsx" excel file
df.to_excel("students.xlsx", index=False)

print("Excel file created successfully.")

Excel file created successfully.

STEP 6 : SAVE DATA AS JASON FILE

In [48]:
# save data in "students.json" json file
df.to_json("students.json", orient="records", index=4)

print("json file created successfully.")

json file created successfully.

STEP 7 : READ THE CSV FILE

In [47]:
# read the "students.csv" csv file
df_csv = pd.read_csv("students.csv")

df_csv

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 8 : READ THE EXCEL FILE

In [46]:
# read the "students.xlsx" excel file
df_excel = pd.read_excel("students.xlsx")

df_excel

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 9 : READ THE JSON FILE

In [45]:
#  read the "students.json" json file
df_json = pd.read_json("students.json")

df_json

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 10 : DISPLAY THE FIRST FIVE RECORDS

In [44]:
# dispaly first five records using head()
df_csv.head()

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84

STEP 11 : DISPLAY THE LAST FIVE RECORDS

In [43]:
# dispaly last five records using tail()
df_csv.tail()

    ID     Name  Age         City  Marks
1  102    Janvi   22      navsari     92
2  103   bhavya   24       valsad     78
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 12 : DISPLAY DATASET OF INFORMATION

In [42]:
#  Display information about the Dataset
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      6 non-null      int64
 1   Name    6 non-null      object
 2   Age     6 non-null      int64
 3   City    6 non-null      object
 4   Marks   6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

STEP 13 : DISPLAY STATISTICAL SUMMARY

In [41]:
# display numerical columns
df_csv.describe()

               ID        Age      Marks
count    6.000000   6.000000   6.000000
mean   103.500000  25.500000  86.166667
std      1.870829   4.636809   4.996666
min    101.000000  20.000000  78.000000
25%    102.250000  22.500000  84.250000
50%    103.500000  24.500000  86.500000
75%    104.750000  28.750000  89.500000
max    106.000000  32.000000  92.000000

STEP 14 : DISPLAY DATASET SHAPE

In [40]:
# dispaly size of dataset
df_csv.shape

(6, 5)

STEP 15 : DISPLAY COLUMNS NAMES

In [39]:
# dispaly all columns
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

STEP 16 : DISPLAY DATA TYPES

In [38]:
# dispaly datatype of columns
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

STEP 17 : CHECK FOR ANY MISSING VALUE

In [37]:
# check missing value of columns and count the number of missing value
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

STEP 18 : DISPLAY A SINGLE COLUMN

In [36]:
# dispaly the single "name" column
df_csv["Name"]

0      Himay
1      Janvi
2     bhavya
3       kavy
4    dharmik
5       sneh
Name: Name, dtype: object

STEP 19 : DISPLAYS MULTIPLE COLUMMS

In [35]:
# dispaly multiple columns named is "Name" and "Marks"
df_csv[["Name", "Marks"]]

      Name  Marks
0    Himay     85
1    Janvi     92
2   bhavya     78
3     kavy     88
4  dharmik     84
5     sneh     90

STEP 20 : FILTER RECORDS

In [34]:
# display the student whose marks are greater than 80
df_csv[df_csv["Marks"] > 80]

    ID     Name  Age         City  Marks
0  101    Himay   20        surat     85
1  102    Janvi   22      navsari     92
3  104     kavy   25         vapi     88
4  105  dharmik   30  gandhinagar     84
5  106     sneh   32        Delhi     90

STEP 21 : CALCULATE AVG MARKS

In [33]:
# dispaly the avg marks
df_csv["Marks"].mean()

np.float64(86.16666666666667)

STEP 22 : SORT DATA

In [32]:
# dispaly the students by Marks in descending order
df_csv.sort_values(by="Marks", ascending=False)

    ID     Name  Age         City  Marks
1  102    Janvi   22      navsari     92
5  106     sneh   32        Delhi     90
3  104     kavy   25         vapi     88
0  101    Himay   20        surat     85
4  105  dharmik   30  gandhinagar     84
2  103   bhavya   24       valsad     78